# Generated by Django 4.1.1 on 2022-09-23 09:36

from django.db import migrations

def capitalize(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    for product in Product.objects.all():
        product.name = product.name.capitalize()
        product.save()
class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
       migrations.RunPython(
        capitalize,
        migrations.RunPython.noop
        ),
    ]
